name: CICD react in nginx

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              run: docker build -t ionhashicorp/react-test-01
            - name: Publish image to docker hub
              run: docker push ionhashicorp/react-test-01:latest
